# Generated by Django 4.0.6 on 2022-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Flia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
