# Generated by Django 4.0.6 on 2022-07-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Flia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
