# Generated by Django 4.0.6 on 2022-07-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Flia', '0002_alter_familia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_nac',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
